# example docker-compose file
version: '3'
services:
  bird:
    image: ibhde/bird4
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    network_mode: host
    volumes:
      - /path/to/config:/etc/bird:ro

  bird6:
    image: ibhde/bird6
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    network_mode: host
    volumes:
      - /path/to/config:/etc/bird:ro
